### ISSUE TITLE
mstpr-brainbot - If the stake token minted from portfolio balance systems total collateral is not decreased

### ISSUE THREAD

**Issue by sherlock-admin4** [sherlock-audit/2024-05-elfi-protocol-judging#105]
mstpr-brainbot

Medium

# If the stake token minted from portfolio balance systems total collateral is not decreased

## Summary
When users deposit to the portfolio vault, the total collateral held in the system increases. Users can mint stake tokens using their current portfolio vault tokens instead of depositing new ones. In this case, the collateral held by the user decreases and is counted as liquidity in the stake token. However, this decrease is not reflected in the total collateral held by the system.
## Vulnerability Detail
When a user mints stake tokens using their portfolio vault balance, they submit the `walletRequestTokenAmount` as "0" and specify the `requestTokenAmount` to mint the stake tokens. In the `MintProcess::_transferFromAccount`, which is responsible for decreasing the total collateral held by the users, the amount is decreased but the system's total collateral is not updated:
```solidity
function _transferFromAccount(address account, address token, uint256 needAmount) internal {
        .
        -> tradeAccount.subTokenIgnoreUsedAmount(token, needAmount, Account.UpdateSource.TRANSFER_TO_MINT);
        int256 availableValue = tradeAccount.getCrossAvailableValue();
        if (availableValue < 0) {
            revert Errors.MintFailedWithBalanceNotEnough(account, token);
        }
    }
```
## Impact
Total collateral hold by the system will not be correct. Breaks the core contract functionality.
## Code Snippet
https://github.com/sherlock-audit/2024-05-elfi-protocol/blob/8a1a01804a7de7f73a04d794bf6b8104528681ad/elfi-perp-contracts/contracts/process/AssetsProcess.sol#L81-L120

https://github.com/sherlock-audit/2024-05-elfi-protocol/blob/8a1a01804a7de7f73a04d794bf6b8104528681ad/elfi-perp-contracts/contracts/process/MintProcess.sol#L131-L137

https://github.com/sherlock-audit/2024-05-elfi-protocol/blob/8a1a01804a7de7f73a04d794bf6b8104528681ad/elfi-perp-contracts/contracts/process/MintProcess.sol#L264-L274
## Tool used

Manual Review

## Recommendation
Decrease the total collateral hold since the used portfolio vault tokens are no longer collateral in the system

Duplicate of #113

**Comment by sherlock-admin2** [comment]
The Lead Senior Watson signed off on the fix.
