### ISSUE TITLE
Timenov - Attacker can get tokens without depositing.

### ISSUE THREAD

**Issue by sherlock-admin4** [sherlock-audit/2024-05-elfi-protocol-judging#12]
Timenov

Medium

# Attacker can get tokens without depositing.

## Summary
The flow of the `AccountFacet` smart contract is as follows:

1. User deposits token A.
2. When withdrawing, user calls `createWithdrawRequest` passing the token and the amount he wants to withdraw.
3. Keeper bot automatically calls `executeWithdraw` and transfers the tokens to the user.

However there is no validation if that user has deposited that much amount of that token.

## Vulnerability Detail
As there is no validation and as per my discussion with the protocol team, the keeper is `a bot that automatically executes requests`, a malicious user can get tokens for free. The flow mentioned above can be bypassed and there is no need for a user to first deposit in order to withdraw.

## Impact
User getting tokens for free.

## Code Snippet
https://github.com/sherlock-audit/2024-05-elfi-protocol/blob/8a1a01804a7de7f73a04d794bf6b8104528681ad/elfi-perp-contracts/contracts/facets/AccountFacet.sol#L40C1-L46C6

https://github.com/sherlock-audit/2024-05-elfi-protocol/blob/8a1a01804a7de7f73a04d794bf6b8104528681ad/elfi-perp-contracts/contracts/facets/AccountFacet.sol#L48C1-L57C6

## Tool used
Manual Review

## Recommendation
Keep track of the deposited amount for tokens by users and add validations when creating a withdraw request.

**Comment by nevillehuang** [comment]
Invalid, tracked [here](https://github.com/sherlock-audit/2024-05-elfi-protocol/blob/8a1a01804a7de7f73a04d794bf6b8104528681ad/elfi-perp-contracts/contracts/process/AssetsProcess.sol#L132)
