### ISSUE TITLE
4b - Incorrect check logic in `validateExecutionFeeLimit()`

### ISSUE THREAD

**Issue by sherlock-admin2** [sherlock-audit/2024-05-elfi-protocol-judging#127]
4b

Medium

# Incorrect check logic in `validateExecutionFeeLimit()`

## Summary
In  `validateExecutionFeeLimit()`  the transaction will revert most of the time because the `executionFee` is below the `gasLimit*tx.gasprice` most of the time as stated by sponsor
## Vulnerability Detail
Sponsor confirmed normally the `executionFee` has to be less than `gasLimit * tx.gasprice`, but in the code snippet we can see that the [`validateExecutionFeeLimit()`](https://github.com/sherlock-audit/2024-05-elfi-protocol/blob/main/elfi-perp-contracts/contracts/process/GasProcess.sol#L51-L56) tries to validate the `executionFee` to be greater than  `gasLimit * tx.gasprice`.  as a result it will cause a revert in other functionalities.
## Impact
This function will cause unwanted/ false reverts to happen because of the wrong check
## Code Snippet
```solidity
    function validateExecutionFeeLimit(uint256 executionFee, uint256 gasLimit) external view {
        if (executionFee < gasLimit * tx.gasprice) {
            revert Errors.ExecutionFeeNotEnough();
        }
    }
```

## Tool used

Manual Review

## Recommendation
the check should be readjusted to be greater than instead

**Comment by nevillehuang** [comment]
Invalid, no issue here executionFee must cover minimum gasLimit * gasPrice
