### ISSUE TITLE
4b - `LpPool::subCollateralBaseToken()` will broken when `collateralAmount` > `tokenAmount`

### ISSUE THREAD

**Issue by sherlock-admin4** [sherlock-audit/2024-05-elfi-protocol-judging#129]
4b

Medium

# `LpPool::subCollateralBaseToken()` will broken when `collateralAmount` > `tokenAmount`

## Summary
The [`LpPool::subCollateralBaseToken()`](https://github.com/sherlock-audit/2024-05-elfi-protocol/blob/main/elfi-perp-contracts/contracts/storage/LpPool.sol#L173-L205) will break whenever `collateralAmount > tokenAmount`
## Vulnerability Detail
In [`LpPool::subCollateralBaseToken()`](https://github.com/sherlock-audit/2024-05-elfi-protocol/blob/main/elfi-perp-contracts/contracts/storage/LpPool.sol#L173-L205) there is an if/else statement that handles the removing of collateral, 
```solidity
       if (tokenAmount == collateralAmount) {
            balance.collateralTokenAmounts.remove(collateral);
        } else {
            balance.collateralTokenAmounts.set(collateral, tokenAmount - collateralAmount);
        }
```
 in the above code block we can see that the cases handled doesn't take into consideration a case where `collateralAmount > tokenAmount` and in this case `tokenAmount-collateralAmount` will be arithmetically impossible since they are of types uint256.
## Impact
This will lead to an unwanted revert and disruption of functionality.
## Code Snippet
```solidity
   function subCollateralBaseToken(
        Props storage self,
        uint256 amount,
        address collateral,
        uint256 collateralAmount
    ) external {
        require(
            self.baseTokenBalance.amount >= amount && self.baseTokenBalance.liability >= amount,
            "sub failed with balance not enough"
        );

        TokenBalance storage balance = self.baseTokenBalance;
        PoolTokenUpdateEventCache memory cache = _convertBalanceToCache(self.stakeToken, self.baseToken, balance);
        balance.amount -= amount;
        balance.liability -= amount;
        cache.amount = balance.amount;
        cache.liability = balance.liability;
        uint256 tokenAmount = balance.collateralTokenAmounts.get(collateral);
        if (tokenAmount == collateralAmount) {
            balance.collateralTokenAmounts.remove(collateral);
        } else {
            balance.collateralTokenAmounts.set(collateral, tokenAmount - collateralAmount);
        }

        _emitPoolUpdateEvent(cache);
        emit PoolCollateralTokenUpdateEvent(
            self.stakeToken,
            collateral,
            tokenAmount,
            tokenAmount - collateralAmount,
            ChainUtils.currentBlock()
        );
    }
```
## Tool used

Manual Review

## Recommendation
The if/else statement has to be readjusted to handle that situation

**Comment by nevillehuang** [comment]
Invalid, if you don't have sufficient collateral in balance to subtract `collateralAmount`, reverting is correct.
