### ISSUE TITLE
4b - Unvalidated amount can break the function  `LpPool::subStableToken`

### ISSUE THREAD

**Issue by sherlock-admin4** [sherlock-audit/2024-05-elfi-protocol-judging#132]
4b

Medium

# Unvalidated amount can break the function  `LpPool::subStableToken`

## Summary
In [`LpPool::subStableToken`](https://github.com/sherlock-audit/2024-05-elfi-protocol/blob/main/elfi-perp-contracts/contracts/storage/LpPool.sol#L276-L289) the  `amount` is not validated but is subtracted from `self.stableTokenBalances[stableToken].amount`, In cases where the `amount > self.stableTokenBalances[stableToken].amount` this will lead to an underflow thereby causing the function to revert 
## Vulnerability Detail
in `LpPool::subStableToken` we can see there is an absence of a check validating that the amount should always be in the within the `self.stableTokenBalances[stableToken].amount` making it subtractable.

the function goes on to [`self.stableTokenBalances[stableToken].amount -= amount;`](https://github.com/sherlock-audit/2024-05-elfi-protocol/blob/main/elfi-perp-contracts/contracts/storage/LpPool.sol#L282)
in cases where `amount >  self.stableTokenBalances[stableToken].amount` this will revert.
## Impact
This will cause a reversion, disrupting the protocol's functionality.
## Code Snippet
`subStableToken()`

```solidity
    function subStableToken(Props storage self, address stableToken, uint256 amount) external {
        PoolTokenUpdateEventCache memory cache = _convertBalanceToCache(
            self.stakeToken,
            stableToken,
            self.stableTokenBalances[stableToken]
        );
        // @audit what if amount is greater than tokenbalance
@->        self.stableTokenBalances[stableToken].amount -= amount;
        cache.amount = self.stableTokenBalances[stableToken].amount;
        if (self.stableTokenBalances[stableToken].amount == 0) {
            self.stableTokens.remove(stableToken);
            delete self.stableTokenBalances[stableToken];
        }
        _emitPoolUpdateEvent(cache);
    }
```
## Tool used

Manual Review

## Recommendation
A balance check should be implemented.
Or `isSubAmountAllowed()` can be added to check that.

**Comment by nevillehuang** [comment]
Invalid, if there are insufficient balance to substract amount, then reverting is correct
