### ISSUE TITLE
Rhaydden - Oracle Price Management Conflict Leading to Incorrect Withdrawal Calculations

### ISSUE THREAD

**Issue by sherlock-admin3** [sherlock-audit/2024-05-elfi-protocol-judging#134]
Rhaydden

Medium

# Oracle Price Management Conflict Leading to Incorrect Withdrawal Calculations

## Summary

The `executeWithdraw` function sets and clears oracle prices within the function, which can lead to incorrect calculations or behavior for subsequent withdrawal requests that rely on the same oracle prices.

## Vulnerability Detail
Look at this part of the code:

```solidity
function executeWithdraw(uint256 requestId, OracleProcess.OracleParam[] calldata oracles) external override {
    RoleAccessControl.checkRole(RoleAccessControl.ROLE_KEEPER);
    Withdraw.Request memory request = Withdraw.get(requestId);
    if (request.account == address(0)) {
        revert Errors.WithdrawRequestNotExists();
    }
    OracleProcess.setOraclePrice(oracles);
    AssetsProcess.executeWithdraw(requestId, request);
    OracleProcess.clearOraclePrice();
}
```

The `executeWithdraw` function calls `OracleProcess.setOraclePrice(oracles)` before executing the withdrawal and then immediately calls `OracleProcess.clearOraclePrice()` after the withdrawal is executed. This assumes that the oracle prices set by `setOraclePrice` are only relevant for the specific withdrawal request being executed.

However, if there are multiple withdrawal requests pending and they rely on the same oracle prices, clearing the oracle prices immediately after executing one withdrawal could lead to incorrect calculations for the subsequent withdrawals.

Let's loook at this scenario: 
1. Withdrawal request A is created, requiring oracle prices X and Y.
2. Withdrawal request B is created, also requiring oracle prices X and Y.
3. The `executeWithdraw` function is called for request A, setting the oracle prices X and Y using `setOraclePrice`.
4. The withdrawal for request A is executed successfully.
5. The `clearOraclePrice` function is called, removing the oracle prices X and Y.
6. The `executeWithdraw` function is called for request B, but the required oracle prices X and Y are no longer available, potentially leading to incorrect calculations or errors.

## Impact

This issue can result in incorrect calculations or errors for subsequent withdrawal requests that depend on the same oracle prices. If the oracle prices are cleared prematurely, the required prices may not be available for the next withdrawal request, potentially leading to unexpected behavior or financial losses.

## Code Snippet

https://github.com/sherlock-audit/2024-05-elfi-protocol/blob/main/elfi-perp-contracts/contracts/facets/AccountFacet.sol#L48-L57

## Tool used

Manual Review

## Recommendation

Consider managing the oracle prices separately from the withdrawal execution process. Instead of setting and clearing the oracle prices within the `executeWithdraw` function, consider the following approach:

1. Retrieve the necessary oracle prices before calling `executeWithdraw`.
2. Pass the retrieved oracle prices as arguments to the `executeWithdraw` function.
3. Use the provided oracle prices within the `executeWithdraw` function for the specific withdrawal request.
4. Remove the `setOraclePrice` and `clearOraclePrice` calls from the `executeWithdraw` function.

**Comment by nevillehuang** [comment]
Invalid, each execution of withdrawal conforms to a single requestID and is atomic, so I don't see the issue here
