### ISSUE TITLE
uint6 - Lack of input validation allows user to mint unlimited token

### ISSUE THREAD

**Issue by sherlock-admin4** [sherlock-audit/2024-05-elfi-protocol-judging#135]
uint6

Medium

# Lack of input validation allows user to mint unlimited token

## Summary
malicious user can mint unlimited amount of token 
## Vulnerability Detail
https://github.com/sherlock-audit/2024-05-elfi-protocol/blob/main/elfi-perp-contracts/contracts/facets/StakeFacet.sol#L21

The function takes ```walletRequestTokenAmount``` as one of it parameters however, the function does not validate the ```walletRequestTokenAmount``` against user's actual token balance before proceeding to minting process only checks if the ```walletRequestTokenAmount``` is greater than 0
https://github.com/sherlock-audit/2024-05-elfi-protocol/blob/main/elfi-perp-contracts/contracts/facets/StakeFacet.sol#L44

Consider a scenario where malicious user, ```Alice```, manipulate the ```walletRequestTokenAmount``` value by inflating the amount let's say 1000000000 USDC, even though ```Alice``` has 10 USDC the contract would assume that ```Alice ``` has deposited the inflated amount and proceed the minting process.

Hence that ```Alice``` deposit native token, the manipulated value will be wrapped using the IWETH and transfers the manipulated wrapped tokens to the target vault address due to the improper handling of token decimals before transferring tokens to the vault.

https://github.com/sherlock-audit/2024-05-elfi-protocol/blob/main/elfi-perp-contracts/contracts/process/AssetsProcess.sol#L70

Since that the contract did not check ```Alice``` token balance, ```Alice``` balance was inflated by providing large value for ```walletRequestTokenAmount``` due to the improper handling of token decimals before transferring tokens to the vault, Alice's balance will be inflated, allowing ```Alice``` to mint more tokens.

Here's the Arb sepolia tx hash that store the manipulated value  from the https://sepolia.elfi.xyz Testnet!!

https://sepolia.arbiscan.io/tx/0x0319497c2d995d542d257e792db738bc343c4f53db1194b223f58c3ed0eeb645#eventlog
## Impact
manipulating the return value of ```walletRequestTokenAmount``` would allow malicious user to mint more tokens than they have, leading to unauthorized minting draining the  protocol.
## Code Snippet

```solidity
   function createMintStakeTokenRequest(MintStakeTokenParams calldata params) external payable override nonReentrant {
        if (params.requestTokenAmount == 0) {
            revert Errors.MintWithAmountZero();
        }
        if (params.stakeToken == address(0)) {
            revert Errors.MintWithParamError();
        }

        address account = msg.sender;
        address token = params.requestToken;
        if (CommonData.getStakeUsdToken() == params.stakeToken) {
            if (!UsdPool.isSupportStableToken(token)) {
                revert Errors.MintTokenInvalid(params.stakeToken, token);
            }
        } else if (CommonData.isStakeTokenSupport(params.stakeToken)) {
            LpPool.Props storage pool = LpPool.load(params.stakeToken);
            if (pool.baseToken != token) {
                revert Errors.MintTokenInvalid(params.stakeToken, token);
            }
        } else {
            revert Errors.StakeTokenInvalid(params.stakeToken);
        }

        if (params.walletRequestTokenAmount > 0) {
            require(!params.isNativeToken || msg.value == params.walletRequestTokenAmount, "Deposit eth amount error!");
            AssetsProcess.depositToVault(
                AssetsProcess.DepositParams(
                    account,
                    params.requestToken,
                    params.walletRequestTokenAmount,
                    params.isCollateral ? AssetsProcess.DepositFrom.MINT_COLLATERAL : AssetsProcess.DepositFrom.MINT,
                    params.isNativeToken
                )
            );
        }

        (uint256 walletRequestTokenAmount, bool isExecutionFeeFromLpVault) = MintProcess
            .validateAndDepositMintExecutionFee(account, params);
        if (params.requestTokenAmount < walletRequestTokenAmount) {
            revert Errors.MintWithParamError();
        }

        MintProcess.createMintStakeTokenRequest(
            params,
            account,
            token,
            walletRequestTokenAmount,
            isExecutionFeeFromLpVault
        );
    }
 ```
    
## Tool used

Manual Review

## Recommendation
Consider implementing a check for a user token balance before proceeding with the minting process, ensure that ```walletRequestTokenAmount``` does not exceed  user's actual token balance.

**Comment by nevillehuang** [comment]
Invalid, will revert [here](https://github.com/sherlock-audit/2024-05-elfi-protocol/blob/main/elfi-perp-contracts/contracts/process/AssetsProcess.sol#L76)
