### ISSUE TITLE
Rhaydden - Execution fee not cleared after order cancellation leading to potential fee payment for canceled orders

### ISSUE THREAD

**Issue by sherlock-admin4** [sherlock-audit/2024-05-elfi-protocol-judging#138]
Rhaydden

Medium

# Execution fee not cleared after order cancellation leading to potential fee payment for canceled orders

## Summary
In `OrderFacet.sol`, the `executionFee` associated with an order is not cleared when the order is canceled. This can lead to situations where a keeper's executeOrder transaction, broadcast before the order cancellation, can still process the executionFee even though the order has already been canceled.

## Vulnerability Detail

Look at this part of the code:

```solidity
function cancelOrder(uint256 orderId, bytes32 reasonCode) external override {
        uint256 startGas = gasleft();
        Order.OrderInfo memory order = Order.get(orderId);
        if (order.account == address(0)) {
            revert Errors.OrderNotExists(orderId);
        }
        bool isKeeper = RoleAccessControl.hasRole(RoleAccessControl.ROLE_KEEPER);
        if (!isKeeper && order.account != msg.sender) {
            revert Errors.OrderNotExists(orderId);
        }

        CancelOrderProcess.cancelOrder(orderId, order, reasonCode);

        if (isKeeper) {
            GasProcess.processExecutionFee(
                GasProcess.PayExecutionFeeParams(
                    order.isExecutionFeeFromTradeVault
                        ? IVault(address(this)).getTradeVaultAddress()
                        : IVault(address(this)).getPortfolioVaultAddress(),
                    order.executionFee,
                    startGas,
                    msg.sender,
                    order.account
                )
            );
        } else {
            VaultProcess.transferOut(
                order.isExecutionFeeFromTradeVault
                    ? IVault(address(this)).getTradeVaultAddress()
                    : IVault(address(this)).getPortfolioVaultAddress(),
                AppConfig.getChainConfig().wrapperToken,
                address(this),
                order.executionFee
            );
            VaultProcess.withdrawEther(order.account, order.executionFee);
        }
    }
```

When a user cancels an order using the `cancelOrder` function, the function calls the `CancelOrderProcess.cancelOrder` function to perform the actual cancellation. However, the [`CancelOrderProcess.cancelOrder`](https://github.com/sherlock-audit/2024-05-elfi-protocol/blob/main/elfi-perp-contracts/contracts/process/CancelOrderProcess.sol#L96-L112) does not clear the `executionFee` associated with the order.

Consider the following scenario:
1. A user places an order with an associated `executionFee`.
2. A keeper, seeing the order, broadcasts an `executeOrder` transaction to execute the order and claim the `executionFee`.
3. Around the same time, the user decides to cancel the order and calls the `cancelOrder` function.
4. The user's `cancelOrder` transaction is mined before the keeper's `executeOrder` transaction.
5. Although the order is now canceled, the keeper's `executeOrder` transaction still processes because the `executionFee` is still associated with the order.

As a result, the keeper can claim the `executionFee` even though the order has already been canceled, leading to a loss of funds for the contract owner.

## Impact
The contract owner may lose funds due to execution fees being paid out for canceled orders. Keepers may also be incentivized to monitor the mempool for `cancelOrder` transactions and attempt to front-run them with `executeOrder` transactions to claim the execution fee before the order is canceled.

## Code Snippet
https://github.com/sherlock-audit/2024-05-elfi-protocol/blob/main/elfi-perp-contracts/contracts/facets/OrderFacet.sol#L89-L125

https://github.com/sherlock-audit/2024-05-elfi-protocol/blob/main/elfi-perp-contracts/contracts/process/CancelOrderProcess.sol#L96-L112

## Tool used
Manual Review

## Recommendation
In the `CancelOrderProcess.cancelOrder` function, clear the executionFee associated with the order by setting it to `0` to make sure that any pending executeOrder transactions will not be able to process the executionFee after the order has been canceled.

**Comment by 0xELFi** [comment]
When the user cancels the order, the order information will be deleted. If the keeper calls execute again, it will be reverted, indicating that the order does not exist.

**Comment by nevillehuang** [comment]
Invalid per sponsor comments
