### ISSUE TITLE
tedox - Changing the supported collateral can result in locked tokens

### ISSUE THREAD

**Issue by sherlock-admin4** [sherlock-audit/2024-05-elfi-protocol-judging#174]
tedox

Medium

# Changing the supported collateral can result in locked tokens

## Summary
If a token is changed from being supported collateral to not being supported collateral, user's funds can get locked inside the contract.

## Vulnerability Detail
During depositing and withdrawing the protocol checks if the token is currently allowed to be used as collateral. Having this check during deposit is not an issue but if the list of supported collateral tokens changes after a user has called `AccountFacet::deposit` and before they have called `AccountFacet::createWithdrawRequest` can result in their tokens being locked inside the contract because of the check inside `AssetsProcess::withdraw` 

```solidity
   function withdraw(uint256 requestId, WithdrawParams memory params) public {
        if (params.amount == 0) {
            revert Errors.AmountZeroNotAllowed();
        }
 @>     if (!AppTradeTokenConfig.getTradeTokenConfig(params.token).isSupportCollateral) {
            revert Errors.OnlyCollateralSupported();
        }
        ...
```
Because of that, users will not be able to withdraw their funds until the token is supported again.

## Impact

Funds can get locked inside the contract for an undefined period of time.  Changing the token back to supported collateral for a short period of time so that the users can withdraw their tokens is also not a solution as that would require limiting them from calling `AccountFacet::deposit` which currently has no protection in order to ensure that there wouldn't be any more locked funds.

## Code Snippet
https://github.com/sherlock-audit/2024-05-elfi-protocol/blob/main/elfi-perp-contracts/contracts/facets/AccountFacet.sol#L40-L57
https://github.com/sherlock-audit/2024-05-elfi-protocol/blob/main/elfi-perp-contracts/contracts/process/AssetsProcess.sol#L122-L128

## Tool used

Manual Review

## Recommendation

Remove the check inside `AssetsProcess::withdraw` as it is not needed. The users cannot have any funds that are not or have not been supported collateral and the transaction would revert either way on the next check as `accountProps.getTokenAmount(params.token)` would be 0 by default. That would also result in a minimal gas optimization.

```solidity
        Account.Props storage accountProps = Account.load(params.account);

        if (accountProps.getTokenAmount(params.token) < params.amount) {
            revert Errors.WithdrawWithNoEnoughAmount();
        }
```

```diff
-        if (!AppTradeTokenConfig.getTradeTokenConfig(params.token).isSupportCollateral) {
-          revert Errors.OnlyCollateralSupported();
-      }
 ```

**Comment by nevillehuang** [comment]
Invalid, config role has the appropriate relevant permissions, they are trusted not to be malicious

> The set functions in ConfigFacet can only be called by the Config Role, such as setPoolConfig.

**Comment by sherlock-admin2** [comment]
The Lead Senior Watson signed off on the fix.
