### ISSUE TITLE
KrisRenZo - Protocol assumes tokenPrice decimals to always be 8. However not, all chainlink prices have 8 decimals

### ISSUE THREAD

**Issue by sherlock-admin2** [sherlock-audit/2024-05-elfi-protocol-judging#187]
KrisRenZo

Medium

# Protocol assumes tokenPrice decimals to always be 8. However not, all chainlink prices have 8 decimals

## Summary
The protocol assumes tokenPrice decimals to always be 8. However not, all chainlink prices have 8 decimals.

## Vulnerability Detail
The protocol source its price feed from chainlink but assumes all feeds share the same  8 decimal precision. This assumption is incorrect. Although, non-ETH pairs usually have 8 decimals, while ETH pairs have 18 decimals.

## Impact
Incorrect price precision can lead to over or under estimation of asset value.

## Code Snippet
The `OracleProcess::getLatestUsdUintPrice` always return price with 8 decimal precision, and it is passed it `CalUtils::tokenToUsd` as it is when converting between crypto tokens to stableToken
https://github.com/sherlock-audit/2024-05-elfi-protocol/blob/8a1a01804a7de7f73a04d794bf6b8104528681ad/elfi-perp-contracts/contracts/process/PositionMarginProcess.sol#L385-L386
```js
	uint256 marginTokenPrice = OracleProcess.getLatestUsdUintPrice(position.marginToken, !position.isLong);
	uint256 reduceMarginAmount = CalUtils.usdToToken(reduceMargin, decimals, marginTokenPrice);
```

https://github.com/sherlock-audit/2024-05-elfi-protocol/blob/8a1a01804a7de7f73a04d794bf6b8104528681ad/elfi-perp-contracts/contracts/utils/CalUtils.sol#L76
```js
	function tokenToUsd(uint256 tokenAmount, uint8 tokenDecimals, uint256 tokenPrice) external pure returns (uint256) {
		return tokenAmount.mul(tokenPrice).mul(PRICE_TO_WEI).div(10 ** tokenDecimals);
	} 
```

## Tool used

Manual Review

## Recommendation
Factor in the token price precision in its calculation.

**Comment by nevillehuang** [comment]
Invalid, all Non-ETH pairs have 8 decimals, and `getLatestUsdUintPrice` is retreiving USD price, so no issue here
