### ISSUE TITLE
Chuchulev - Solidity pragma should be specific, not wide

### ISSUE THREAD

**Issue by sherlock-admin3** [sherlock-audit/2024-05-elfi-protocol-judging#2]
Chuchulev

Medium

# Solidity pragma should be specific, not wide

## Summary
[L-1]: Solidity pragma should be specific, not wide so risk of vulnerabilities can be reduced.

## Vulnerability Detail
- Found in contracts/facets/RoleAccessControlFacet.sol [Line: 21](contracts/facets/RoleAccessControlFacet.sol#L21)

- Found in contracts/chain/ArbSys.sol [Line: 2](contracts/chain/ArbSys.sol#L2)

	```solidity
	pragma solidity ^0.8.18;
	```

## Impact
Low

## Tool used
Aderyn

Manual Review

## Recommendation
Consider using a specific version of Solidity in your contracts instead of a wide version. For example, instead of `pragma solidity ^0.8.0;`, use `pragma solidity 0.8.0;`

**Comment by nevillehuang** [comment]
Invalid, informational, no direct impact on protocol
