### ISSUE TITLE
AnasTur - Uncontrolled Slippage Exposes Users to Unfavorable Trade Executions

### ISSUE THREAD

**Issue by sherlock-admin3** [sherlock-audit/2024-05-elfi-protocol-judging#215]
AnasTur

High

# Uncontrolled Slippage Exposes Users to Unfavorable Trade Executions

## Summary

The `SwapProcess.sol` contract lacks a mechanism for users to define their slippage tolerance, exposing them to the risk of receiving significantly less of the output token than expected during swaps.

## Vulnerability Detail

The `SwapProcess.sol` library is responsible for executing token swaps within the protocol. However, it does not incorporate a user-defined slippage tolerance parameter. This means users have no control over the maximum acceptable price deviation during a swap. 

Currently, the protocol relies on a global `swapSlipperTokenFactor` in `AppTradeConfig`. This factor likely acts as a small buffer to adjust the minimum expected output, but it's a protocol-level setting and does not provide users with the ability to set their own slippage limits.

## Impact

In volatile market conditions, the absence of slippage protection can result in users receiving far less of the desired token than they anticipated. This leads to a poor user experience and potential financial losses. Users are exposed to unfavorable trade executions, as they cannot define their risk tolerance for price fluctuations during swaps.
https://github.com/sherlock-audit/2024-05-elfi-protocol/blob/main/elfi-perp-contracts/contracts/process/SwapProcess.sol#L15
## Code Snippet

```solidity
// SwapProcess.sol

// ... (other code)

function swap(ISwap.SwapParams calldata params) external returns (ISwap.SwapResult memory result) {
    // ... (swap execution logic without slippage check)
}

// ... (other code)
```

## Tool used

Manual Review

## Recommendation

1.  **Introduce `maxSlippage` Parameter:**
    *   Add a `maxSlippage` parameter to the `SwapParams` struct in the `ISwap.sol` interface. This parameter should be a `uint256` representing the maximum percentage slippage the user is willing to accept (e.g., 100 for 1%, 500 for 5%).

2.  **Implement Slippage Check:**
    *   In the `SwapProcess.swap` function, calculate the minimum acceptable output amount based on the `maxSlippage` parameter.
    *   Before finalizing the swap, compare the actual output amount received with the calculated minimum. If the actual amount is less than the minimum, revert the transaction.

**Comment by nevillehuang** [comment]
Invalid, `SwapFacet.sol` OOS
