### ISSUE TITLE
SAAJ - createWithdrawRequest revert for native token

### ISSUE THREAD

**Issue by sherlock-admin2** [sherlock-audit/2024-05-elfi-protocol-judging#217]
SAAJ

High

# createWithdrawRequest revert for native token

## Summary
User can loss all the ```ETH``` deposited into contract as ```deposit``` function allow depositing of eth but ```createWithdrawRequest``` does not allow passing ```address(0)``` when making withdrawal request.
## Vulnerability Detail
In ```AccountFacet``` contract  ```deposit``` function allows user to deposit ether into contract by passing ```address(0)```.
```solidity
        bool isNativeToken = token == address(0);
```
However, the ```address(0)``` argument is not allowed to be passed in ```createWithdrawRequest``` that makes a depositor unable to withdraw their deposited ```eth``` balance.
```solidity
 function createWithdrawRequest(address token, uint256 amount) external override {
        AddressUtils.validEmpty(token);
        if (amount == 0) {
            revert Errors.AmountZeroNotAllowed();
        }
        AssetsProcess.createWithdrawRequest(token, amount);
    }
```
## Impact
When a user is unable to call the ```createWithdrawRequest``` with passing all his funds will stuck leading to direct loss of reward.

The loss is because ```eth``` is allowed to be deposited by passing ```address(0)``` in ```deposit``` function but not allowed to be withdrawn in ```createWithdrawRequest``` function.

## Code Snippet
https://github.com/sherlock-audit/2024-05-elfi-protocol/blob/main/elfi-perp-contracts/contracts/facets/AccountFacet.sol#L40
## Tool used

Manual Review

## Recommendation
The recommendation is made to allow passing ```address(0)``` arguments when calling ```createWithdrawRequest``` function.
```diff
    function createWithdrawRequest(address token, uint256 amount) external override {
-        AddressUtils.validEmpty(token);
        if (amount == 0) {
            revert Errors.AmountZeroNotAllowed();
        }
        AssetsProcess.createWithdrawRequest(token, amount);
    }

```

**Comment by nevillehuang** [comment]
Invalid, native ETH deposits is wrapped into WETH as seen [here](https://github.com/sherlock-audit/2024-05-elfi-protocol/blob/main/elfi-perp-contracts/contracts/process/AssetsProcess.sol#L72)
