### ISSUE TITLE
SAAJ - cancelUpdatePositionMarginRequest does not refund eth

### ISSUE THREAD

**Issue by sherlock-admin4** [sherlock-audit/2024-05-elfi-protocol-judging#219]
SAAJ

High

# cancelUpdatePositionMarginRequest does not refund eth

## Summary
```cancelUpdatePositionMarginRequest``` does not refund amount that is deposited into contract through ```createUpdatePositionMarginRequest```.

## Vulnerability Detail
When a user calls ```cancelUpdatePositionMarginRequest``` to cancel request created for updating position it does not take into account refunding of amount that was deposited while creating the request made through ```createUpdatePositionMarginRequest``` function.
```solidity
    function cancelUpdatePositionMarginRequest(uint256 requestId, bytes32 reasonCode) external override {
        uint256 startGas = gasleft();
        RoleAccessControl.checkRole(RoleAccessControl.ROLE_KEEPER);
        UpdatePositionMargin.Request memory request = UpdatePositionMargin.get(requestId);
        if (request.account == address(0)) {
            revert Errors.UpdatePositionMarginRequestNotExists();
        }
        PositionMarginProcess.cancelUpdatePositionMarginRequest(requestId, request, reasonCode);
        GasProcess.processExecutionFee(
            GasProcess.PayExecutionFeeParams(
                request.isExecutionFeeFromTradeVault
                    ? IVault(address(this)).getTradeVaultAddress()
                    : IVault(address(this)).getPortfolioVaultAddress(),
                request.executionFee,
                startGas,
                msg.sender,
                request.account
            )
        );
    }
```

## Impact
Lack of refund mechanism will cause direct loss to the user cancelling update request for the deposited amount while making call to the ```createUpdatePositionMarginRequest``` function.

## Code Snippet
https://github.com/sherlock-audit/2024-05-elfi-protocol/blob/main/elfi-perp-contracts/contracts/facets/PositionFacet.sol#L87

## Tool used

Manual Review

## Recommendation
The recommendation is made to have refund mechanism in the ```cancelUpdatePositionMarginRequest``` function to refund any deposited amount made by user while making deposit to the contract for creating update position request.

**Comment by nevillehuang** [comment]
Invalid, only keepers can cancel margin request, not any  user in which the gas fee is refunded for the call.
