### ISSUE TITLE
tedox - `swapPortfolioToPayLiability` is vulnerable to sandwich attacks

### ISSUE THREAD

**Issue by sherlock-admin2** [sherlock-audit/2024-05-elfi-protocol-judging#22]
tedox

High

# `swapPortfolioToPayLiability` is vulnerable to sandwich attacks

## Summary
When the contract uses Uniswap Router in order to swap tokens it does not account for slippage.

## Vulnerability Detail
`            ISwapRouter.ExactInputSingleParams memory callSwapParams = ISwapRouter.ExactInputSingleParams({
                tokenIn: params.fromTokens[i],
                tokenOut: params.toToken,
                fee: 3000,
                recipient: params.toTokenAddress,
                deadline: block.timestamp,
                amountIn: useFromAmount,
                amountOutMinimum: 0,
                sqrtPriceLimitX96: 0
            });
 uint256 amountOut = ISwapRouter(uniswapRouter).exactInputSingle(callSwapParams);
`

When calling `exactInputSingle` in order to swap tokens to repay all liabilities the function does not specify a minimum amount of tokens to receive or a maximum price to execute the swap at making it vulnerable to frontrunning and the so called sandwich attack.

## Impact
Malicious users can track the contracts transactions and frontrun it every time it tries to make a swap in order to gain funds and as a consequence make the contract make a swap at a higher price.

## Code Snippet
[https://github.com/sherlock-audit/2024-05-elfi-protocol/blob/main/elfi-perp-contracts/contracts/process/AssetsProcess.sol#L167-L172
https://github.com/sherlock-audit/2024-05-elfi-protocol/blob/main/elfi-perp-contracts/contracts/process/AssetsProcess.sol#L122-L155](https://github.com/sherlock-audit/2024-05-elfi-protocol/blob/main/elfi-perp-contracts/contracts/process/SwapProcess.sol#L15-L67)

## Tool used
Manual Review

## Recommendation
Set values to `amountOutMinimum` and `sqrtPriceLimitX96`

**Comment by nevillehuang** [comment]
Invalid, OOS, `swap()` is only used within the OOS `SwapFacet` contract as seen [here](https://github.com/sherlock-audit/2024-05-elfi-protocol/blob/8a1a01804a7de7f73a04d794bf6b8104528681ad/elfi-perp-contracts/contracts/facets/SwapFacet.sol#L76)
