### ISSUE TITLE
pwning_dev - Missing Return Value Checks on External Calls

### ISSUE THREAD

**Issue by sherlock-admin3** [sherlock-audit/2024-05-elfi-protocol-judging#227]
pwning_dev

High

# Missing Return Value Checks on External Calls

pwning_dev

# Missing Return Value Checks on External Calls
## Summary
External calls in depositToVault, such as IWETH.deposit and TransferUtils.transfer, do not check for return values or handle potential failures.

## Vulnerability Detail
The contract performs several external calls, such as token transfers and WETH deposits, without checking the return values or ensuring that the calls were successful. This lack of error handling can lead to the contract behaving incorrectly if any of these external calls fail. In the context of financial transactions and asset management, such failures can have severe consequences, including the loss of funds or incorrect accounting of balances.

## Code Snippet
https://github.com/sherlock-audit/2024-05-elfi-protocol/blob/main/elfi-perp-contracts/contracts/process/AssetsProcess.sol#L72C9-L72C67
https://github.com/sherlock-audit/2024-05-elfi-protocol/blob/main/elfi-perp-contracts/contracts/process/AssetsProcess.sol#L74C9-L74C73

## Tool used
Vs code 
Manual Review
## Recommendation
```solidity
 if (params.isNativeToken) {
        address wrapperToken = AppConfig.getChainConfig().wrapperToken;
        require(wrapperToken == params.token, 

> "Deposit with token error!");

        IWETH(wrapperToken).deposit{ value: params.amount }();
        require(IWETH(wrapperToken).deposit{ value: params.amount }(), "WETH deposit failed");
        token = wrapperToken;
        require(TransferUtils.transfer(token, targetAddress, params.amount), "Token transfer failed");
    } else {
        require(IERC20(token).safeTransferFrom(params.account, targetAddress, params.amount), "Token transferFrom failed");
    }
```

**Comment by nevillehuang** [comment]
Invalid transfer in WETH will only revert during insufficient token balances and deposit will never revert
