### ISSUE TITLE
ZeroTrust - DECREASE order can not be canceled.

### ISSUE THREAD

**Issue by sherlock-admin2** [sherlock-audit/2024-05-elfi-protocol-judging#241]
ZeroTrust

Medium

# DECREASE order can not be canceled.

## Summary
DECREASE order can not be canceled.
## Vulnerability Detail
```javascript
 function cancelOrder(
        uint256 orderId,
        bytes32 reasonCode
    ) external override {
        uint256 startGas = gasleft();
        Order.OrderInfo memory order = Order.get(orderId);
        if (order.account == address(0)) {
            revert Errors.OrderNotExists(orderId);
        }
        bool isKeeper = RoleAccessControl.hasRole(
            RoleAccessControl.ROLE_KEEPER
        );
        if (!isKeeper && order.account != msg.sender) {
            revert Errors.OrderNotExists(orderId);
        }

@>>     CancelOrderProcess.cancelOrder(orderId, order, reasonCode);
        //skip ...
    }
```

```javascript
function cancelOrder(uint256 orderId, Order.OrderInfo memory order, bytes32 reasonCode) external {
        Account.Props storage accountProps = Account.load(order.account);
        accountProps.delOrder(orderId);
        Order.remove(orderId);
@@>        if (Order.PositionSide.INCREASE == order.posSide && order.isCrossMargin) {
            accountProps.subOrderHoldInUsd(order.orderMargin);
@@>        } else if (Order.PositionSide.INCREASE == order.posSide && !order.isCrossMargin) {
            VaultProcess.transferOut(
                IVault(address(this)).getTradeVaultAddress(),
                order.marginToken,
                order.account,
                order.orderMargin
            );
        }
        emit CancelOrderEvent(orderId, order, reasonCode);
    }
```
We can see that only INCREASE type orders are allowed to be canceled, while DECREASE type orders cannot be canceled. This affects the integrity of the system’s functionality and will also accumulate a large number of orders that cannot be executed. When a user changes their mind and wants to cancel their DECREASE type orders, the system does not allow it, which is incomprehensible. This could also cause potential financial losses for the user.
## Impact
This affects the integrity of the system’s functionality and will also accumulate a large number of orders that cannot be executed. This could also cause potential financial losses for the user.
## Code Snippet
https://github.com/sherlock-audit/2024-05-elfi-protocol/blob/main/elfi-perp-contracts/contracts/facets/OrderFacet.sol#L89

https://github.com/sherlock-audit/2024-05-elfi-protocol/blob/main/elfi-perp-contracts/contracts/process/CancelOrderProcess.sol#L96
## Tool used

Manual Review

## Recommendation
DECREASE type orders should be allowed to be canceled

**Comment by nevillehuang** [comment]
Invalid, there is nothing reverting a cancellation of a DECREASE type order
