### ISSUE TITLE
joicygiore - The `Keeper` role is a restricted role, but can call All two-phase commit functions (functions starting with 'execute' in Facet), and most methods have `OracleProcess.OracleParam[] calldata oracles`. For such methods, keeper Price manipulation is possible

### ISSUE THREAD

**Issue by sherlock-admin2** [sherlock-audit/2024-05-elfi-protocol-judging#25]
joicygiore

High

# The `Keeper` role is a restricted role, but can call All two-phase commit functions (functions starting with 'execute' in Facet), and most methods have `OracleProcess.OracleParam[] calldata oracles`. For such methods, keeper Price manipulation is possible

## Summary
The `Keeper` role is a restricted role, but can call All two-phase commit functions (functions starting with 'execute' in Facet), and most methods have `OracleProcess.OracleParam[] calldata oracles`. For such methods, keeper Price manipulation is possible
## Vulnerability Detail
For example: 
`OrderFacet::executeOrder()`,keeper can easily complete price manipulation and obtain profits from it.
```js
    function executeOrder(uint256 orderId, OracleProcess.OracleParam[] calldata oracles) external override {
        uint256 startGas = gasleft();
        RoleAccessControl.checkRole(RoleAccessControl.ROLE_KEEPER);
        Order.OrderInfo memory order = Order.get(orderId);
        if (order.account == address(0)) {
            revert Errors.OrderNotExists(orderId);
        }
        OracleProcess.setOraclePrice(oracles);
        OrderProcess.executeOrder(orderId, order);
        OracleProcess.clearOraclePrice();
        GasProcess.processExecutionFee(
            GasProcess.PayExecutionFeeParams(
                order.isExecutionFeeFromTradeVault
                    ? IVault(address(this)).getTradeVaultAddress()
                    : IVault(address(this)).getPortfolioVaultAddress(),
                order.executionFee,
                startGas,
                msg.sender,
                order.account
            )
        );
    }
```
## Impact
The `Keeper` role is a restricted role, but can call All two-phase commit functions (functions starting with 'execute' in Facet), and most methods have `OracleProcess.OracleParam[] calldata oracles`. For such methods, keeper Price manipulation is possible
## Code Snippet
https://github.com/sherlock-audit/2024-05-elfi-protocol/blob/main/elfi-perp-contracts/contracts/facets/OrderFacet.sol#L66-L87
https://github.com/sherlock-audit/2024-05-elfi-protocol/blob/main/elfi-perp-contracts/contracts/facets/AccountFacet.sol#L48-L57
https://github.com/sherlock-audit/2024-05-elfi-protocol/blob/main/elfi-perp-contracts/contracts/facets/StakeFacet.sol#L72-L99
https://github.com/sherlock-audit/2024-05-elfi-protocol/blob/main/elfi-perp-contracts/contracts/facets/StakeFacet.sol#L124-L153
https://github.com/sherlock-audit/2024-05-elfi-protocol/blob/main/elfi-perp-contracts/contracts/facets/StakeFacet.sol#L155-L179
https://github.com/sherlock-audit/2024-05-elfi-protocol/blob/main/elfi-perp-contracts/contracts/facets/PositionFacet.sol#L61-L85
https://github.com/sherlock-audit/2024-05-elfi-protocol/blob/main/elfi-perp-contracts/contracts/facets/PositionFacet.sol#L149-L173
## Tool used

Manual Review

## Recommendation
It is recommended to redesign the method of price acquisition. Keeper should not be passed as a parameter. Even if there is price verification inside the update price method, as long as it is not 100% accurate, the keeper will be profitable.

**Comment by nevillehuang** [comment]
Invalid, keeper is trusted to set oracle prices and maintain 2 step commit
