### ISSUE TITLE
nikhil840096 - Underflow Vulnerability in `AssetsProcess.sol:deposit` function.

### ISSUE THREAD

**Issue by sherlock-admin2** [sherlock-audit/2024-05-elfi-protocol-judging#31]
nikhil840096

High

# Underflow Vulnerability in `AssetsProcess.sol:deposit` function.

## Summary
There is a potential underflow vulnerability in a calculation involving `params.amount` and `repayAmount`. Both variables are of type `uint256`, and if repayAmount exceeds params.amount, the subtraction will cause an underflow. Given that the contract is using Solidity version 0.8.18, this underflow will cause the transaction to revert.

## Vulnerability Detail
When user tries to deposit using contract `AccountFacet.sol` function `deposit` it triggers `deposit`  function of  `AssetProcess.sol` library. Inside `deposit` function of library `AssetProcess.sol`  there is a calculation for `repayLiability` the amount of liability the user has to pay
```solidity
uint256 repayAmount = accountProps.repayLiability(token);
```
Then `updateAllPositionFromBalanceMargin` function is called in library  `PositionMarginProcess` which updates the margin positions
```solidity
PositionMarginProcess.updateAllPositionFromBalanceMargin(
                    requestId,
                    params.account,
                    token,
                    (params.amount - repayAmount).toInt256(),
                    ""
                );
```
The vulnerability lies here   `(params.amount - repayAmount).toInt256()` if  `repayAmount`(uint256) increases than `params.amount`(uint256), this will lead to underflow and the transaction will revert as the the version used for solidity is `^0.8.18`.

## Impact
* Users will not be unable to deposit tokens if the repayAmount exceeds the params.amount, leading to failed transactions.
* The inability of users to deposit or repay liabilities will lead to significant financial losses for the protocol. Unresolved liabilities may accumulate, and the protocol may incur additional costs in managing these unsettled debts

## Code Snippet
https://github.com/sherlock-audit/2024-05-elfi-protocol/blob/main/elfi-perp-contracts/contracts/process/AssetsProcess.sol#L113
## Tool used

Manual Review

## Recommendation
```diff
-  (params.amount - repayAmount).toInt256(),
+ params.amount >= repayAmount ? (params.amount - repayAmount).toInt256() : -((repayAmount - params.amount).toInt256()),
```

**Comment by nevillehuang** [comment]
Invalid, if insufficient deposited amount is used to cover repayment of liability, reverting is correct
