### ISSUE TITLE
eeshenggoh - Keeper cannot call execute function due to invalid access control implementation

### ISSUE THREAD

**Issue by sherlock-admin4** [sherlock-audit/2024-05-elfi-protocol-judging#39]
eeshenggoh

High

# Keeper cannot call execute function due to invalid access control implementation

## Summary
As per README:
>Admin Role (TRUSTED): Used for managing other Roles
Keeper Role (RESTRICTED): Only used for executing two-phase commits and scheduled tasks.

> For permissioned functions, please list all checks and requirements that will be made before calling the function.
All two-phase commit functions (functions starting with 'execute' in Facet) can only be called by the Keeper Role, such as executeOrder().
All first-phase cancellation functions can only be called by the Keeper Role (except for cancelOrder, which users can also use to cancel orders).

We know that Keeper Role != Admin Role. Problem arise when keeper tries to execute request.
## Vulnerability Detail
In `StakeFacet::executeMintStakeToken` which calls `MintProcess::executeMintStakeToken`. Within that function, it will transfer tokens from the LP vault to a token pool which is only callable by an account with the `ADMIN_ROLE`. Whenever keeper role call the two step execution function it reverts.
```solidity
    function executeMintStakeToken( 
        uint256 requestId,
        Mint.Request memory mintRequest
    ) external returns (uint256 stakeAmount) {
    -- SNIP --
        if (!mintRequest.isCollateral && mintRequest.walletRequestTokenAmount > 0) {
            IVault(address(this)).getLpVault().transferOut( //@audit-issue Require Admin Role
                mintRequest.requestToken,
                mintRequest.stakeToken,
                mintRequest.walletRequestTokenAmount
            );
        }
```
```solidity
    function transferOut(address token, address receiver, uint256 amount) external onlyRole(ADMIN_ROLE) {
        if (receiver == address(this)) {
            revert AddressSelfNotSupported(receiver);
        }
        TransferUtils.transfer(token, receiver, amount);
    }
```
## Impact
Denial of service when keeper bot call execution function. All requests will not be executed.
## Code Snippet
https://github.com/sherlock-audit/2024-05-elfi-protocol/blob/main/elfi-perp-contracts/contracts/vault/Vault.sol#L16
## Tool used

Manual Review

## Recommendation
Create another access control modifier that allows keeper bot to execute the function.

**Comment by 0xELFi** [comment]
The admin role here is different from the system's admin role. The admin of the vault is the diamond address, which means that only smart contracts can transfer vault assets

**Comment by goheesheng** [comment]
Hi, I believe this should be considered a valid report for the following reasons:

1) I inquired whether the stakeFacet contract had any roles, and was informed that it did not.
2) The README.md file is ambiguous and does not clearly specify the existence of two distinct types of admin roles, which led to the submission.
![image](https://github.com/sherlock-audit/2024-05-elfi-protocol-judging/assets/77826239/99a574a7-7101-4385-8e55-3c5f53b9f754)

**Comment by nevillehuang** [comment]
Invalid per sponsor comments. Speculaton on admin configurations

**Comment by goheesheng** [comment]
Could this be seen as unjust for the Watsons? The documentation lacks clarity, and the README.md is typically our primary reference. The developer did not provide clarification on the distinction between admin roles. Should I not receive credit for incorporating their discussion?

As stated by the developer: "If that's the case, why wasn't it mentioned in the README as well?"

"The admin role in this context differs from the system's admin role. The vault's admin is the diamond address, limiting asset transfers to smart contracts only."
