### ISSUE TITLE
joicygiore - `AccountFacet::batchUpdateAccountToken()` lacks calling permission. Anyone can call this method to add any number of tokens to the account.

### ISSUE THREAD

**Issue by sherlock-admin2** [sherlock-audit/2024-05-elfi-protocol-judging#4]
joicygiore

High

# `AccountFacet::batchUpdateAccountToken()` lacks calling permission. Anyone can call this method to add any number of tokens to the account.

## Summary
`AccountFacet::batchUpdateAccountToken()` lacks calling permission. Anyone can call this method to add any number of tokens to the account.
## Vulnerability Detail
`AccountFacet::batchUpdateAccountToken()` lacks calling permission. Anyone can call this method to add any number of tokens to the account.
```js
@>    function batchUpdateAccountToken(AssetsProcess.UpdateAccountTokenParams calldata params) external override {
        AddressUtils.validEmpty(params.account);
        AssetsProcess.updateAccountToken(params);
    }
```
The function will call the following method to update the account status. There is no other check except `accountProps.checkExists()`, and any token can be added to the account.
```js
    function updateAccountToken(UpdateAccountTokenParams calldata params) external {
        Account.Props storage accountProps = Account.load(params.account);
@>        accountProps.checkExists();
        for (uint256 i; i < params.tokens.length; i++) {
            if (params.changedTokenAmounts[i] == 0) {
                continue;
            }
            if (params.changedTokenAmounts[i] > 0) {
                accountProps.addToken(params.tokens[i], params.changedTokenAmounts[i].toUint256());
                accountProps.repayLiability(params.tokens[i]);
            } else {
                accountProps.subToken(params.tokens[i], (-params.changedTokenAmounts[i]).toUint256());
            }
        }
    }
```
## Impact
AccountFacet::batchUpdateAccountToken() lacks calling permission. Anyone can call this method to add any number of tokens to the account.
## Code Snippet
https://github.com/sherlock-audit/2024-05-elfi-protocol/blob/8a1a01804a7de7f73a04d794bf6b8104528681ad/elfi-perp-contracts/contracts/facets/AccountFacet.sol#L68-L71
## Tool used

Manual Review

## Recommendation
Add calling permission restrictions

Duplicate of #28

**Comment by pronobis4** [comment]
dup: #193
