### ISSUE TITLE
mstpr-brainbot - Updating leverage does not accrues the latest borrowing fees for the market

### ISSUE THREAD

**Issue by sherlock-admin3** [sherlock-audit/2024-05-elfi-protocol-judging#47]
mstpr-brainbot

High

# Updating leverage does not accrues the latest borrowing fees for the market

## Summary
When leverage is updated the borrowed amount changes in pool hence, the borrowing per token should be updated to the latest time to have an even borrowing rate. 
## Vulnerability Detail
When leverage is increased or decreased for any position the pools total borrowing rates will change. Hence, before the leverage the latest borrowing fees must accrue to maintain the correct accounting for the fees per Masterchef alike staking mechanism. 

For example, if a position has 100 tokens as margin and 2x leverage then the position is borrowing 100 tokens from the pool. 
When the same position is updated and levered up to 10x now the margin is 20 tokens and account is borrowing 180 tokens from the pool. 
If the latest interaction with the pool was 1 day ago and the total borrows were "X" for the pool, the borrowing rate should be updated right before the leverage is updated by the user's call to accrue the previous day's borrowing rate. However, since the code does not do this and borrow balances now increase, the next time the fees are updated it will assume the borrowing rate was the same as it was 1 day ago. This is incorrect and will create higher/lower and unfair distribution fees, which can lead to insolvent positions, lower/higher yields for LPers, and all sorts of unexpected outcomes.
## Impact
As per my last sentence in vulnerability details section:
"This is incorrect and will create higher/lower and unfair distribution fees, which can lead to insolvent positions, lower/higher yields for LPers, and all sorts of unexpected outcomes."
## Code Snippet
https://github.com/sherlock-audit/2024-05-elfi-protocol/blob/8a1a01804a7de7f73a04d794bf6b8104528681ad/elfi-perp-contracts/contracts/process/PositionMarginProcess.sol#L134-L229
## Tool used

Manual Review

## Recommendation
Call these functions in the beginning of updating leverage as its done in OrderProcess.
https://github.com/sherlock-audit/2024-05-elfi-protocol/blob/8a1a01804a7de7f73a04d794bf6b8104528681ad/elfi-perp-contracts/contracts/process/MarketProcess.sol#L29-L73

Duplicate of #63

**Comment by sherlock-admin2** [comment]
The Lead Senior Watson signed off on the fix.
