### ISSUE TITLE
mstpr-brainbot - Updating leverage does not accrue the latest borrowing fees and skips updating the borrowing fee per token for the user

### ISSUE THREAD

**Issue by sherlock-admin4** [sherlock-audit/2024-05-elfi-protocol-judging#48]
mstpr-brainbot

High

# Updating leverage does not accrue the latest borrowing fees and skips updating the borrowing fee per token for the user

## Summary
When leverage is updated by user the latest realized borrowing fees and borrowing fee per token should be updated for the user because the borrowing rate will change.
## Vulnerability Detail
When account is increasing or decreasing its leverage it updates the entire borrowed amount of the pools and rate changes. Hence, the accounts `realizedFees` and borrowing fee per token must need to be updated to have a fair system for users. 
## Impact
Because of the unpredictable fee accruals, it can lead to premature liquidations for accounts or profits that should be lower.
For example, if user last interaction was a week ago and the total borrowing fees were 100 tokens for the this time interval after the change can be miscounted as 10 tokens or 200 tokens depending on user increasing or decreasing the leverage.
## Code Snippet
https://github.com/sherlock-audit/2024-05-elfi-protocol/blob/8a1a01804a7de7f73a04d794bf6b8104528681ad/elfi-perp-contracts/contracts/process/PositionMarginProcess.sol#L134-L229
## Tool used

Manual Review

## Recommendation
Add this function to update leverage flywheel to make sure users borrowing per token is updated.
https://github.com/sherlock-audit/2024-05-elfi-protocol/blob/8a1a01804a7de7f73a04d794bf6b8104528681ad/elfi-perp-contracts/contracts/process/FeeProcess.sol#L76-L100

Duplicate of #63

**Comment by sherlock-admin2** [comment]
The Lead Senior Watson signed off on the fix.
