### ISSUE TITLE
mstpr-brainbot - The `autoReducePositions` function is not updating the market funding and pool borrowing fees prior to closing the position

### ISSUE THREAD

**Issue by sherlock-admin2** [sherlock-audit/2024-05-elfi-protocol-judging#52]
mstpr-brainbot

High

# The `autoReducePositions` function is not updating the market funding and pool borrowing fees prior to closing the position

## Summary
When positions are decreased via `autoReducePositions` call, borrowing and funding fees are not updated which leads to inaccurate fee accounting for the users.
## Vulnerability Detail
The markets overall borrowing and funding rates are updated in the casual flow of decrease position via these function calls:
```solidity
function _executeDecreaseOrder(
        uint256 orderId,
        Order.OrderInfo memory order,
        Symbol.Props memory symbolProps
    ) internal {
        .
        .
        -> MarketProcess.updateMarketFundingFeeRate(symbolProps.code);
       ->  MarketProcess.updatePoolBorrowingFeeRate(symbolProps.stakeToken, position.isLong, order.marginToken);
}
```

This update is very crucial because it will accrue the interest up to the current time for both funding and borrowing fees, which are essential for determining users' and pools' profit/loss. However, as we can observe, the `autoReducePositions` function skips updating the rates and directly closes the position.
## Impact
Latest accrued interest will not be updated for the user and previous values will be used. User can get a higher profit or a lesser loss or completely opposites of these. This will also break the entire Masterchef alike flywheel and affect other users as well. Hence, high.
## Code Snippet
https://github.com/sherlock-audit/2024-05-elfi-protocol/blob/8a1a01804a7de7f73a04d794bf6b8104528681ad/elfi-perp-contracts/contracts/facets/PositionFacet.sol#L196-L216
https://github.com/sherlock-audit/2024-05-elfi-protocol/blob/8a1a01804a7de7f73a04d794bf6b8104528681ad/elfi-perp-contracts/contracts/process/OrderProcess.sol#L414-L451
## Tool used

Manual Review

## Recommendation
Add these two functions before calling the autoReducePositions:
```solidity
MarketProcess.updateMarketFundingFeeRate(symbolProps.code);
MarketProcess.updatePoolBorrowingFeeRate(symbolProps.stakeToken, position.isLong, order.marginToken);
```

Duplicate of #63

**Comment by mstpr** [comment]
Escalate

This should be marked as high. Closing a position without accruing the funding and borrowing fees will result in:

- Unfair profit/loss for the trader
- Unfair borrowing fees for the Lp'ers
- Depending on how late it's called, it can even create insolvency

This is also at the same level as issue #63, so there's no reason to keep this marked as medium.

**Comment by sherlock-admin3** [comment]
> 
> Escalate
> 
> This should be marked as high. Closing a position without accruing the funding and borrowing fees will result in:
> 
> - Unfair profit/loss for the trader
> - Unfair borrowing fees for the Lp'ers
> - Depending on how late it's called, it can even create insolvency
> 
> This is also at the same level as issue #63, so there's no reason to keep this marked as medium.

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by nevillehuang** [comment]
@0xELFi @0xELFi02 How often would `autoReducePositions` be called to reduce risk? Trying to assess likelihood here. If often I believe this can be high, but would be a duplicate of #63, given they are pointing to the same root cause of lacking updates of borrowing fees but in different functionalities.

**Comment by WangSecurity** [comment]
@0xELFi @0xELFi02 could you provide your thoughts on the above?

**Comment by 0xELFi** [comment]
"autoReducePositions" is used by the risk control module and is triggered based on certain conditions. When a user's total profits exceed a certain proportion of the pool, for example, 50%, the user's profitable positions will be sorted by profit rate. A certain number of high-profit positions will be selected for profit-taking to mitigate the risk of the entire pool incurring losses.

**Comment by 0xELFi** [comment]
The occurrence frequency is very low and is related to extreme one-sided market movements and the depth of the liquidity pool

**Comment by WangSecurity** [comment]
Thank you very much, to address the second point from [this](https://github.com/sherlock-audit/2024-05-elfi-protocol-judging/issues/52#issuecomment-2211629358) comment:

> would be a duplicate of https://github.com/sherlock-audit/2024-05-elfi-protocol-judging/issues/63, given they are pointing to the same root cause of lacking updates of borrowing fees but in different functionalities

I agree with this, indeed the problem is in different places of the code, but the underlying issue is the same, as well as the fix and impact. Correct me if it's wrong.

Since the escalation asked to just update the severity of the finding, while the decision is to duplicate this issue with #63, the escalation will be rejected.

**Comment by WangSecurity** [comment]
Result:
High
Duplicate of #63

**Comment by sherlock-admin2** [comment]
Escalations have been resolved successfully!

Escalation status:
- [mstpr](https://github.com/sherlock-audit/2024-05-elfi-protocol-judging/issues/52/#issuecomment-2210787722): rejected

**Comment by sherlock-admin2** [comment]
The Lead Senior Watson signed off on the fix.
