### ISSUE TITLE
joicygiore - `OrderFacet::cancelOrder()` does not check the order status. Even stop-loss and take-profit orders can be directly exited, which will cause huge losses to users' funds.

### ISSUE THREAD

**Issue by sherlock-admin3** [sherlock-audit/2024-05-elfi-protocol-judging#74]
joicygiore

High

# `OrderFacet::cancelOrder()` does not check the order status. Even stop-loss and take-profit orders can be directly exited, which will cause huge losses to users' funds.

## Summary
`OrderFacet::cancelOrder()` does not check the order status. Even stop-loss and take-profit orders can be directly exited, which will cause huge losses to users' funds.
## Vulnerability Detail
After communicating with the sponsor, it is defined that if the order execution fails, the keeper can call the following method to exit the order
```js
// OrderFacet::cancelOrder()
    function cancelOrder(uint256 orderId, bytes32 reasonCode) external override {
        uint256 startGas = gasleft();
        Order.OrderInfo memory order = Order.get(orderId);
        if (order.account == address(0)) {
            revert Errors.OrderNotExists(orderId);
        }
@>        bool isKeeper = RoleAccessControl.hasRole(RoleAccessControl.ROLE_KEEPER);
        if (!isKeeper && order.account != msg.sender) {
            revert Errors.OrderNotExists(orderId);
        }
@>        CancelOrderProcess.cancelOrder(orderId, order, reasonCode);

// <snip>
    }
```
If we look at the call flow of `CancelOrderProcess::cancelOrder()`, we will see that this method does not match the status according to the order type.
```js
   enum Type {
        NONE, 
        MARKET, 
        LIMIT, 
        STOP 
    }
    function cancelOrder(uint256 orderId, Order.OrderInfo memory order, bytes32 reasonCode) external {
        Account.Props storage accountProps = Account.load(order.account);
        accountProps.delOrder(orderId);
        Order.remove(orderId);
        if (Order.PositionSide.INCREASE == order.posSide && order.isCrossMargin) {
            accountProps.subOrderHoldInUsd(order.orderMargin);
        } else if (Order.PositionSide.INCREASE == order.posSide && !order.isCrossMargin) {
            VaultProcess.transferOut(
                IVault(address(this)).getTradeVaultAddress(),
                order.marginToken,
                order.account,
                order.orderMargin
            );
        }
        emit CancelOrderEvent(orderId, order, reasonCode);
    }
```
We can assume a situation:
1. The user creates a stop loss and take profit order
2. The keeper executes the order sent by the user and fails to execute
3. The keeper calls `OrderFacet::cancelOrder()` due to the failure of order execution. Since there is no order status verification, the order request is deleted.
4. The price reaches the stop loss and take profit price set by the user, but the order request has been deleted and will never be executed. The price continues to fluctuate, continuing to cause losses to users.
## Impact
`OrderFacet::cancelOrder()` does not check the order status. Even stop-loss and take-profit orders can be directly exited, which will cause huge losses to users' funds.
## Code Snippet
https://github.com/sherlock-audit/2024-05-elfi-protocol/blob/main/elfi-perp-contracts/contracts/facets/OrderFacet.sol#L89-L125
https://github.com/sherlock-audit/2024-05-elfi-protocol/blob/main/elfi-perp-contracts/contracts/process/CancelOrderProcess.sol#L96-L111
## Tool used

Manual Review

## Recommendation
Add order status check and refine the execution process of `CancelOrderProcess::cancelOrder()`. Normally, as long as the user account is in a healthy state, only the user address has the authority to exit the stop loss, take profit and other limit orders set by it. The keeper should not have the authority to exit this type of order. Even if the keeper is trusted, this situation should not happen, not to mention that the keeper is not trusted.

**Comment by 0xELFi** [comment]
When the keeper executes an order, if the stop order is not executed due to the trigger price, cancelOrder will not be called; it will only be called for other exceptions.
