### ISSUE TITLE
eeshenggoh - pairToken prices are not cleared, utilizing expired staled price

### ISSUE THREAD

**Issue by sherlock-admin3** [sherlock-audit/2024-05-elfi-protocol-judging#8]
eeshenggoh

High

# pairToken prices are not cleared, utilizing expired staled price

## Summary
Elfi use their own offline oracle mechanism, where the oracle protocol administrator is only responsible for providing the oracle price.
The logic implementation includes setting the price, executing the function, finally clearing the price.

> Should potential issues, like broken assumptions about function behavior, be reported if they could pose risks in future integrations, even if they might not be an issue in the context of the scope? If yes, can you elaborate on properties/invariants that should hold?
yes

Hence the submission.
## Vulnerability Detail
There are 2 types of prices oracle mainly utilize, `tokenPrices and pairPrices`.

Users can call `PositionFacet::autoReducePositions` to reduce positions. This function internally calls `DecreasePositionProcess::decreasePosition`, which further calls `DecreasePositionProcess::_updateDecreasePosition`.

In `_updateDecreasePosition`, the function checks the token prices, including **pair token prices**. With the price logic in mind, let's focus on the clearing function:

```solidity
    function clearAllPrice(Props storage oracle) external {
        address[] memory tokenAddrs = oracle.tokens.values();
        //@audit-issue
        for (uint256 i; i < tokenAddrs.length; i++) {
            delete oracle.tokenPrices[tokenAddrs[i]];
            delete oracle.preTokenPrices[tokenAddrs[i]]; // changes value to 0, does not remove the element as it uses the key
            oracle.tokens.remove(tokenAddrs[i]); // removes the value from the set, which is fine
        }
    }
```

The `OraclePrices::clearOraclePrice` function is called every time a keeper bot needs to clear token prices. Failing to remove the price could result in an expired price of a pair being stored on the blockchain. If logic loads this expired price, it can lead to difficult-to-detect errors. If a pair with no price is loaded after deletion, it will directly revert.

From the clearing function, the `preTokenPrices`, `pairs` and `pairPrices` are not cleared, which allows expired prices to be used for trading. Whenever a user calls functions to adjust positions, it will always use the stale price:
```solidity
    struct Props {
        EnumerableSet.AddressSet tokens;
        mapping(address => Data) tokenPrices;
        mapping(address => Data) preTokenPrices;
        EnumerableSet.Bytes32Set pairs; //@audit
        mapping(bytes32 => Data) pairPrices;//@audit
    }
```

## Impact
Expired pair prices are used for margin trading.
## Code Snippet
https://github.com/sherlock-audit/2024-05-elfi-protocol/blob/main/elfi-perp-contracts/contracts/process/DecreasePositionProcess.sol#L217
https://github.com/sherlock-audit/2024-05-elfi-protocol/blob/main/elfi-perp-contracts/contracts/storage/OraclePrice.sol#L12
https://github.com/sherlock-audit/2024-05-elfi-protocol/blob/main/elfi-perp-contracts/contracts/storage/OraclePrice.sol#L67
## Tool used

Manual Review

## Recommendation
Ensure that paired prices are cleared too.

Duplicate of #83

**Comment by sherlock-admin2** [comment]
The Lead Senior Watson signed off on the fix.
