### ISSUE TITLE
nikhil840096 - `SwapProcess.sol:swap` have no slippage parameters.

### ISSUE THREAD

**Issue by sherlock-admin2** [sherlock-audit/2024-05-elfi-protocol-judging#85]
nikhil840096

High

# `SwapProcess.sol:swap` have no slippage parameters.

## Summary
While making a swap on UniswapV3 the caller should use the slippage parameter amountOutMinimum and deadline parameter to avoid losing funds.
https://github.com/sherlock-audit/2024-05-elfi-protocol/blob/main/elfi-perp-contracts/contracts/process/SwapProcess.sol#L50-L59
## Vulnerability Detail
`amountOutMinimum` is used to specify the minimum amount of tokens the caller wants to be returned from a swap. Using `amountOutMinimum = 0` tells the swap that the caller will accept a minimum amount of 0 output tokens from the swap, opening up the user to a catastrophic loss of funds via [MEV bot sandwich attacks](https://medium.com/coinmonks/defi-sandwich-attack-explain-776f6f43b2fd).

`deadline` lets the caller specify a deadline parameter that enforces a time limit by which the transaction must be executed. Without a `deadline` parameter, the transaction may sit in the mempool and be executed at a much later time potentially resulting in a worse price for the user.
## Impact
Loss of funds and not getting the correct amount of tokens in return.
## Code Snippet
https://github.com/sherlock-audit/2024-05-elfi-protocol/blob/main/elfi-perp-contracts/contracts/process/SwapProcess.sol#L50-L59
## Tool used
Manual Review
## Recommendation
Use parameters amountOutMinimum and deadline correctly to avoid loss of funds.

**Comment by nevillehuang** [comment]
Invalid, SwapFacet is OOS of this contest

**Comment by Nikhil8400** [comment]
In the protocol readme it is given that if the vulnerability is high and it is in the file of out of scope then it will be considered as a  valid finding [link](https://github.com/sherlock-audit/2024-05-elfi-protocol-Nikhil8400?tab=readme-ov-file#q-should-potential-issues-like-broken-assumptions-about-function-behavior-be-reported-if-they-could-pose-risks-in-future-integrations-even-if-they-might-not-be-an-issue-in-the-context-of-the-scope-if-yes-can-you-elaborate-on-propertiesinvariants-that-should-hold). And this is the critical vulnerability as not providing any deadline can  lead to loss of funds for the user.
