### ISSUE TITLE
newt - Missing access control `clearLiability`

### ISSUE THREAD

**Issue by sherlock-admin3** [sherlock-audit/2024-05-elfi-protocol-judging#89]
newt

Medium

# Missing access control `clearLiability`

## Summary
Unauthorized clearing of liabilities can disrupt the accounting system, allowing liabilities to be incorrectly zeroed out by any user, leading to financial inconsistencies and potential abuse.
## Vulnerability Detail
 Any external user can call this function, which can lead to unauthorized clearing of liabilities. 
## Impact
There is no access control in the provided `clearLiability` function. Any external caller can clear the liability for any token.
## Code Snippet
    function clearLiability(Props storage self, address token) external {
        clearLiability(self, token, UpdateSource.DEFAULT);
    }

https://github.com/sherlock-audit/2024-05-elfi-protocol/blob/main/elfi-perp-contracts/contracts/storage/Account.sol#L227-L229
## Tool used

Manual Review

## Recommendation
Implement access control .

**Comment by nevillehuang** [comment]
Invalid, `Account.sol` is a library where in `clearLiability` is not meant to be called directly. This function is only called [here](https://github.com/sherlock-audit/2024-05-elfi-protocol/blob/8a1a01804a7de7f73a04d794bf6b8104528681ad/elfi-perp-contracts/contracts/process/LiquidationProcess.sol#L167) where the relevant checks is in place
