### ISSUE TITLE
nikhil840096 - Improper Handling of Request ID in  `AssetsProcess.sol:createWithdrawRequest` Function.

### ISSUE THREAD

**Issue by sherlock-admin4** [sherlock-audit/2024-05-elfi-protocol-judging#9]
nikhil840096

Medium

# Improper Handling of Request ID in  `AssetsProcess.sol:createWithdrawRequest` Function.

## Summary
The function `createWithdrawRequest` in library `AssetsProcess.sol` creates a withdraw  request with a unique requestId. The function currently emits the request ID as an event but does not return it directly, which poses several risks and limitations. This approach has several serious implications, including increased complexity for integration, potential loss of critical data, and significant challenges for other contracts attempting to interact with this function.

## Vulnerability Detail
The function `createWithdrawRequest` in library `AssetsProcess` creates a withdraw  request with a unique requestId. But doesn't returns the requestId it just emits an event. Events are not part of the transaction's state but are instead logged on the blockchain. Events can be missed or not indexed properly by nodes, leading to scenarios where the request ID is not captured. This can cause significant issues for users and systems relying on the event log for critical information. Relying on events for critical data means that the calling code must listen to the blockchain events asynchronously, which can complicate the logic and make it more error-prone.

## Impact

* If the event fails to be emitted for some reason (e.g., due to a gas limit issue), the request ID could be lost, leading to inconsistencies.
* Multiple withdrawal requests submitted in a short time frame may lead to race conditions, where the off-chain system fails to properly associate the request ID with the correct transaction.
* Developers need to implement additional logic to capture and store the emitted event data, increasing the complexity of smart contract interactions. This approach can make the code harder to read, maintain, and debug.
* Contracts that integrate with this function cannot directly receive the request ID because it is only emitted as an event. Unlike return values, events do not provide a way for the calling contract to capture the emitted data directly. (Currently not contract is interacting with this contract but in future if some protocol wanted to integrate there code with elfi).

## Code Snippet
https://github.com/sherlock-audit/2024-05-elfi-protocol/blob/main/elfi-perp-contracts/contracts/process/AssetsProcess.sol#L157-L165

## Tool used

Manual Review

## Recommendation
In `AssetsProcess.sol:createWithdrawRequest` return the requestId.

```diff
-  function createWithdrawRequest(address token, uint256 amount) external {
+ function createWithdrawRequest(address token, uint256 amount) external returns(uint256 requestId){ 
-      uint256 requestId = UuidCreator.nextId(WITHDRAW_ID_KEY);
+     requestId = UuidCreator.nextId(WITHDRAW_ID_KEY);
        Withdraw.Request storage request = Withdraw.create(requestId);
        request.account = msg.sender;
        request.token = token;
        request.amount = amount;

        emit CreateWithdrawEvent(requestId, request);
    }
```

Update the `AccountFacet.sol:createWithdrawRequest` function.

```diff
-  function createWithdrawRequest(address token, uint256 amount) external override {
+ function createWithdrawRequest(address token, uint256 amount) external override returns(uint256 requestId) {
        AddressUtils.validEmpty(token);
        if (amount == 0) {
            revert Errors.AmountZeroNotAllowed();
        }
-       AssetsProcess.createWithdrawRequest(token, amount);
+      requestId = AssetsProcess.createWithdrawRequest(token, amount);
    }
```

**Comment by nevillehuang** [comment]
Invalid, no impact. keepers will decide which requestId to execute the 2 step withdrawal
