### ISSUE TITLE
newt - Functions Missing Access Control

### ISSUE THREAD

**Issue by sherlock-admin4** [sherlock-audit/2024-05-elfi-protocol-judging#90]
newt

Medium

# Functions Missing Access Control

## Summary
The `addPosition` and `delPosition` functions are missing access control. Without access control, any external user can call these functions to modify the positions set, 
## Vulnerability Detail
Anyone can call these functions to add or remove positions.
## Impact
This can lead to unauthorized changes
## Code Snippet
    function addPosition(Props storage self, bytes32 position) external {
        if (!self.positions.contains(position)) {
            self.positions.add(position);
        }
    }

    function delPosition(Props storage self, bytes32 position) external {
        self.positions.remove(position);
    }

https://github.com/sherlock-audit/2024-05-elfi-protocol/blob/main/elfi-perp-contracts/contracts/storage/Account.sol#L240-L248
## Tool used

Manual Review

## Recommendation
Implement access control

**Comment by nevillehuang** [comment]
Invalid, `Account.sol` is a library where in `addPosition` and `delPosition`  is not meant to be called directly. It is only called [here](https://github.com/sherlock-audit/2024-05-elfi-protocol/blob/8a1a01804a7de7f73a04d794bf6b8104528681ad/elfi-perp-contracts/contracts/process/OrderProcess.sol#L207) and [here](https://github.com/sherlock-audit/2024-05-elfi-protocol/blob/8a1a01804a7de7f73a04d794bf6b8104528681ad/elfi-perp-contracts/contracts/process/DecreasePositionProcess.sol#L83) respectively.
